name: Security Scan

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  # schedule:
  #   - cron: '0 0 * * 0'  # Run weekly on Sundays at midnight

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install gitleaks detect-secrets bandit safety

    - name: Run Gitleaks
      uses: zricethezav/gitleaks-action@master

    - name: Install git-secrets
      run: |
        git clone https://github.com/awslabs/git-secrets.git
        cd git-secrets
        sudo make install
        cd ..
        rm -rf git-secrets

    - name: Configure git-secrets
      run: |
        git secrets --register-aws
        git secrets --add 'private_key'
        git secrets --add 'api_key'

    - name: Run git-secrets
      run: git secrets --scan

    - name: Run detect-secrets
      run: detect-secrets scan . > detect-secrets-results.txt

    - name: Run Bandit
      run: bandit -r . -f custom > bandit-results.txt

    - name: Run Safety
      run: safety check --full-report > safety-results.txt

    - name: Run npm audit (if package.json exists)
      run: |
        if [ -f package.json ]; then
          npm audit --json > npm-audit-results.json
        else
          echo "No package.json found, skipping npm audit"
        fi

    - name: Run Trivy filesystem scan
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'table'
        output: 'trivy-results.txt'

    - name: Upload scan results
      uses: actions/upload-artifact@v4
      with:
        name: security-scan-results
        path: |
          detect-secrets-results.txt
          bandit-results.txt
          safety-results.txt
          npm-audit-results.json
          trivy-results.txt

    - name: Check for vulnerabilities
      run: |
        if [ -s detect-secrets-results.txt ] || [ -s bandit-results.txt ] || [ -s safety-results.txt ] || [ -s npm-audit-results.json ] || [ -s trivy-results.txt ]; then
          echo "Vulnerabilities found. Please check the scan results."
          exit 1
        else
          echo "No vulnerabilities found."
        fi

