name: Security Scan

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  # schedule:
  #   - cron: '0 0 * * 0'  # Run weekly on Sundays at midnight
permissions: 
  contents: read 
  id-token: write 
  issues: write 
  pull-requests: write
jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags

    - name: Check for GitLeaks
      continue-on-error: true
      id: gitleaks
      uses: gacts/gitleaks@v1  
      with:
        config-path: gitleaks.toml

    - name: Install git-secrets
      run: |
        git clone https://github.com/awslabs/git-secrets.git
        cd git-secrets
        sudo make install
        cd ..
        rm -rf git-secrets
        ls /tmp
        mv /tmp/gitleaks.sarif gitleaks.sarif

    - name: Configure git-secrets
      run: |
        git secrets --register-aws
        git secrets --add 'private_key'
        git secrets --add 'api_key'


    - name: Run git-secrets
      continue-on-error: true
      run: git secrets --scan


    - name: TruffleHog OSS 
      id: trufflehog 
      uses: trufflesecurity/trufflehog@main
      continue-on-error: true 
      with: 
        base: ""
        head: ${{ github.ref_name }}
        extra_args: --json

    - name: Install detect-secrets
      run: |
        python -m pip install detect-secrets

    - name: Run detect-secrets
      continue-on-error: true
      run: |
        ls
        detect-secrets scan . > secrets.json
        cat secrets.json

    # - name: Install Bandit
    #   run: |
    #     python -m pip install bandit

    # - name: Run Bandit
    #   # if: inputs.language == "python" 
    #   continue-on-error: true
    #   run: bandit -r . -f custom > bandit-results.txt

    # - name: Install Safety
    #   run: |
    #     python -m pip install safety

    # - name: Run Safety
    #   # if: inputs.language == "python" 
    #   continue-on-error: true
    #   run: safety check --full-report > safety-results.txt

    # - name: Install npm (for npm audit)
    #   run: |
    #     sudo apt-get update && sudo apt-get install -y npm

    # - name: Run npm audit (if package.json exists)
    #   continue-on-error: true
    #   run: |
    #     if [ -f package.json ]; then
    #       npm audit --json > npm-audit-results.json
    #     else
    #       echo "No package.json found, skipping npm audit"
    #     fi

    - name: Run Trivy scan
      continue-on-error: true
      uses: aquasecurity/trivy-action@0.29.0
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy_report.sarif'
        exit-code: '1'
        severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
        skip-setup-trivy: false

    - name: Post Trivy SARIF findings in the pull request
      if: github.event_name == 'pull_request'
      uses: sett-and-hive/sarif-to-comment-action@v2.0.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}
        pr-number: ${{ github.event.pull_request.number }}
        sarif-file: trivy_report.sarif
        title: Trivy Report        

    - name: Post gitleaks SARIF findings in the pull request
      if: github.event_name == 'pull_request'
      uses: sett-and-hive/sarif-to-comment-action@v2.0.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}
        pr-number: ${{ github.event.pull_request.number }}
        sarif-file: gitleaks.sarif
        title: Git Leaks Report

    - name: Post git-secrets SARIF findings in the pull request
      if: github.event_name == 'pull_request'
      uses: sett-and-hive/sarif-to-comment-action@v2.0.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}
        pr-number: ${{ github.event.pull_request.number }}
        sarif-file: secrets.json
        title: Git Secret Report

    - name: Upload scan results
      continue-on-error: true
      uses: actions/upload-artifact@v4
      with:
        name: security-scan-results
        path: |
          detect-secrets-results.txt
          bandit-results.txt
          safety-results.txt
          npm-audit-results.json
          trivy-results.sarif
          trufflehog-results.json

    - name: Check for vulnerabilities
      run: |
        if [ -s detect-secrets-results.txt ] || [ -s trufflehog-results.json ] || [ -s bandit-results.txt ] || [ -s safety-results.txt ] || [ -s npm-audit-results.json ] || [ -s trivy-results.txt ]; then
          echo "Vulnerabilities found. Please check the scan results."
          exit 1
        else
          echo "No vulnerabilities found."
        fi
